title: BC Nerd
author: Flemming Bakkensen
email: flemming.bakkensen@gmail.com

description: >-
  Let's Nerd Out on Business Central!
baseurl: "/"
url: "https://fbakkensen.github.io"
github_username: FBakkensen

# Theme settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'