title: fbakkensen
author:
  name: Flemming Bakkensen
  email: flemming.bakkensen@gmail.com

description: >-
  Let's Nerd Out.
baseurl: "/"
url: "https://fbakkensen.github.io"
github_username: FBakkensen
show_downloads: false

# Theme settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate

#site
paginate: 5         # Posts per page
paginate_path: "/page:num/"  # URL structure for paginated pages
google_analytics: G-5FQ1BD5CNH # Google Analytics tracking ID

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
excerpt_separator: "<!--more-->"

minima:
  skin: solarized
  show_excerpts: true
  hide_site_feed_link: true
  nav_pages:
    about.md
  social_links:
    - title: fbakkensen at LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/flemmingbakkensen/"
    - title: fbakkensen at X
      icon: x-twitter
      url: "https://x.com/fbakkensen"
    - title: fbakkensen at GitHub
      icon: github
      url: "https://github.com/FBakkensen"
